add notification
stevotvr/phpbb-flair pull request #7
Opened 2018-06-16 21:37 UTC by uriels777

Hey,
I changed a few files in order to add notifications when an admin add a flair to a user.
didn't add a notification for the automatic flairs, yet.

2018-06-17 03:01 UTC, stevotvr requested changes
Thanks for your contribution! I added some comments on some issues that need to be addressed.

2018-06-17 03:01 UTC, stevotvr commented on controller/acp_user_controller.php
> +				$insert = [
Use array() syntax

2018-06-17 03:01 UTC, stevotvr commented on controller/acp_user_controller.php
> +		$this->notification_manager->add_notifications('stevotvr.flair.notification.type.flair', [
Use array() syntax

2018-06-17 03:01 UTC, stevotvr commented on event/main_listener.php
> +	 * @param manager $notification_manager	 	 		  $notification_manager Notification manager
Use fully qualified class names in param and var comments

2018-06-17 03:01 UTC, stevotvr commented on event/main_listener.php
> +	 * @var manager
Use fully qualified class names in param and var comments

2018-06-17 03:01 UTC, stevotvr commented on controller/acp_user_controller.php
> +		[
Use array() syntax

2018-06-17 03:01 UTC, stevotvr commented on controller/acp_user_controller.php
> +	 * @param manager $notification_manager	 	 		  $notification_manager Notification manager
Use fully qualified class names in param and var comments

2018-06-17 03:01 UTC, stevotvr commented on controller/acp_user_controller.php
> +	/** @var \phpbb\log\log */
Check formatting

2018-06-17 03:01 UTC, stevotvr commented on controller/acp_user_controller.php
> +	 * @var manager
Use fully qualified class names in param and var comments

2018-06-17 03:01 UTC, stevotvr commented on event/main_listener.php
> +		$this->notification_manager->mark_notifications([
Use array() syntax

2018-06-17 03:01 UTC, stevotvr commented on notification/type/flair.php
> +	/** @var \phpbb\controller\helper */
Check formatting

2018-06-17 03:01 UTC, stevotvr commented on notification/type/flair.php
> +	 * @var config
Use fully qualified class names in param and var comments

2018-06-17 03:01 UTC, stevotvr commented on notification/type/flair.php
> +	 * @return void
You can omit void return types

2018-06-17 03:01 UTC, stevotvr commented on notification/type/flair.php
> +	public function set_user_loader(\phpbb\user_loader $user_loader)
Missing documentation

2018-06-17 03:01 UTC, stevotvr commented on notification/type/flair.php
> +	 * @return array Array of data ready to be inserted into the database
Nothing is returned by this function

2018-06-17 03:01 UTC, stevotvr commented on operator/flair.php
> +		$flair_name = 'works?';
Leftover debugging?

2018-06-17 03:01 UTC, stevotvr commented on operator/flair_interface.php
> +	public function get_flair_name($flair_id);
Whitespace found at end of line

2018-06-17 03:01 UTC, stevotvr commented on operator/flair.php
> +	}
Whitespace found at end of line

2018-06-17 03:01 UTC, stevotvr commented on ext.php
> +}
Whitespace found at end of line

2018-06-17 03:01 UTC, stevotvr commented on controller/acp_user_controller.php
> + 				if (isset($this->config['flair_notification_'. $id]))
Check indentation

2018-06-17 03:01 UTC, stevotvr commented on notification/type/flair.php
> +use phpbb\notification\type\base;
Unused

2018-06-17 03:01 UTC, stevotvr commented on controller/acp_user_controller.php
> +		]);
Missing closing brace

2018-06-17 17:04 UTC, stevotvr approved these changes

2018-06-18 19:03 UTC, koraldon commented
Awesome for the approval :) any idea when you will merge it?
Also, do you think a notification for automatic badges is needed - I assume in any case it is better to have as a separate PR.

2018-06-18 19:13 UTC, stevotvr commented
Has this been tested? I'm currently waiting for 1.1.0 to be approved for the extension database before I merge anything.

As for automatic badges, I think it might be useful to be notified about those as well.

2018-07-05 14:01 UTC, koraldon commented
We did some testing on this... Waiting to be merged prior to testing on live site...
As it seems it takes a long time for phpbb to approve the extension 1.1., can you merge it before, so we can make progress?

2018-07-05 17:36 UTC, merged

2018-07-05 17:38 UTC, stevotvr commented
Alright I merged it into a new branch. Sorry about the wait.

2018-07-27 22:12 UTC, stevotvr commented
I noticed in the license header you put the name "Example." Was that intended?

2018-07-29 19:47 UTC, uriels777 commented
Not a mistake, but I don't really care. You can delete it if you want.
If you decide to add notification for group assignments I think you should disable them when a user enter a group ( notification when you add flair to the group and not when a user enter a group and recive the flairs).
Do you need help with one of the other enhancements?

2018-07-29 19:58 UTC, stevotvr commented
So your name is Example?

Anyway, yeah that is probably how the group thing would work since those items are passively assigned via a table join. The notification would be triggered by the admin adding the group.

I think I have the other features covered. I should have it done in a few days.

2018-07-29 20:05 UTC, uriels777 commented
My name is Uriel if you want to use it. 
The code was an example, so..

2018-07-29 20:07 UTC, stevotvr commented
Okay that makes sense.

2018-07-29 20:12 UTC, uriels777 commented
Realy!?
Sometimes I even confuse myself.